#!/bin/bash
cd /home/ubuntu/TweetScraper
source ~/.bashrc
export PATH="/home/ubuntu/miniconda3/condabin:$PATH"
ls
conda init
eval "$(conda shell.bash hook)"
conda activate tweetscraper
which python
nohup python -u ./reciever.py > output.log 2>error.logs &
echo "started listening events"