#!/bin/bash
cd /home/ubuntu/TweetScraper
source ~/.bashrc
export PATH="/home/ubuntu/miniconda3/condabin:$PATH"
ls
conda init
eval "$(conda shell.bash hook)"
conda activate tweetscraper
which python
nohup python -u ./receiver.py scraping > scraping.out 2>scraping.err &
nohup python -u ./receiver.py cookies > cookies.out 2>cookies.err &

echo "started listening events"